<a href="https://colab.research.google.com/github/GounLee/BIT-education/blob/master/%EB%B9%84%ED%8A%B8_%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%88%98%EC%A7%91_%EB%B6%84%EC%84%9D_%EC%8B%9C%EA%B0%81%ED%99%9401.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy 모듈을 사용하기 위한 import문
import numpy as np

In [ ]:
ls = [1,2,3,4,5]
arr=np.array(ls)
print(arr)
print(type(arr)) #다차원

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
ls1=[1,2,3]
ls2=[4,7,2]
ls3=ls1+ls2
print(ls3)#파이썬 리스트의 함은 concat

[1, 2, 3, 4, 7, 2]


In [ ]:
arr1=np.array(ls1)
arr2=np.array(ls2)
arr3=arr1+arr2
print(arr3)#numpy의 +연산은 행렬의 +연산을 수행

[5 9 5]


In [ ]:
ls=[1,2,3]
ls2=ls*3
print(ls2)#리스트*수는 원소를 반복해서 나열

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [ ]:
arr=np.array(ls)
arr2= arr*3
print(arr2) #numpy의 ndarray*정수는 행렬*정수 연산을 수행

[3 6 9]


%%time을 마킹하면 수행시간을 측정해줍니다.

In [ ]:
%%time
arr=np.arange(100000)

CPU times: user 803 µs, sys: 0 ns, total: 803 µs
Wall time: 865 µs


In [ ]:
%%time
ls=list(range(100000))

CPU times: user 1.98 ms, sys: 3.29 ms, total: 5.27 ms
Wall time: 5.14 ms


In [ ]:
arr=np.random.randn(2,3)
print(arr)

[[ 0.05129779  0.48129173 -0.34008338]
 [-1.01080238 -1.2968901   0.88179944]]


In [ ]:
arr2=arr*3
arr2

array([[ 0.15389337,  1.44387519, -1.02025015],
       [-3.03240715, -3.89067029,  2.64539833]])

In [ ]:
arr*3 #위와 같은 표현

array([[ 0.15389337,  1.44387519, -1.02025015],
       [-3.03240715, -3.89067029,  2.64539833]])

In [ ]:
arr.shape #구조 확인 2행 3열

(2, 3)

In [ ]:
arr.ndim #차원 확인

2

In [ ]:
arr.dtype #원소 타입 확인

dtype('float64')

In [ ]:
arr=np.array([1,2,3])
print(arr)
print(arr.dtype)

[1 2 3]
int64


In [ ]:
arr=np.array([1,2,3,4.2]) #정수와 실수로 배열을 생성 => 자동으로 실수타입으로 변환
print(arr)
print(arr.dtype)
print(type(arr[0]))

[1.  2.  3.  4.2]
float64
<class 'numpy.float64'>


In [ ]:
arr=np.array([1,2,3,4.2,'a']) #수와 문자열로 구성 => 자동으로 모두 문자열로 변환
print(arr)
print(arr.dtype)
print(type(arr[0]))

['1' '2' '3' '4.2' 'a']
<U32
<class 'numpy.str_'>


다차원 배열 생성

In [ ]:
ls=[1,2,3]
arr=np.array(ls) #리스트를 입력 인자로 ndarray 개체 생성
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
ls=[[1,2,3],[2,5,6]]
arr=np.array(ls) #리스트를 입력 인자로 ndarray 개체 생성
print(arr)
print(type(arr))

[[1 2 3]
 [2 5 6]]
<class 'numpy.ndarray'>


In [ ]:
arr=np.zeros(10)
print(arr)
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
구조: (10,)
차원: 1
원소 형식: float64


In [ ]:
arr=np.zeros((3,6))
print(arr)
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
구조: (3, 6)
차원: 2
원소 형식: float64


In [ ]:
arr=np.ones((3,6))
print(arr)
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
구조: (3, 6)
차원: 2
원소 형식: float64


In [ ]:
arr=np.arange(20)
print(arr)
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
구조: (20,)
차원: 1
원소 형식: int64


In [ ]:
arr=np.arange(3,20,4)
print(arr)
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

[ 3  7 11 15 19]
구조: (5,)
차원: 1
원소 형식: int64


원소 타입

In [ ]:
arr=np.array([1,2,3])
print(type(arr[0]),type(arr[1]),type(arr[2]))
print(arr.dtype)

<class 'numpy.int64'> <class 'numpy.int64'> <class 'numpy.int64'>
int64


In [ ]:
arr=np.array([1,2,4.2])
print(type(arr[0]),type(arr[1]),type(arr[2]))
print(arr.dtype)

<class 'numpy.float64'> <class 'numpy.float64'> <class 'numpy.float64'>
float64


In [ ]:
arr=np.array([1,2,4.2],dtype=np.int32)#dtype인자를 이용하여 명시적으로 원소 형식 결정
print(type(arr[0]),type(arr[1]),type(arr[2]))
print(arr.dtype)
print(arr)

<class 'numpy.int32'> <class 'numpy.int32'> <class 'numpy.int32'>
int32
[1 2 4]


산술연산

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("==========")
arr2=arr*arr
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


In [ ]:
arr2=arr-arr
print(arr2)

[[0 0 0]
 [0 0 0]]


In [ ]:
arr2=1/arr
print(arr2)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [ ]:
arr2=arr**0.5
print(arr2)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [ ]:
arr1 = np.array([1,2,3]) # 같은 행끼리 비교해서 > , < 비교 -> True,False 
arr2 = np.array([4,0,2])
fillter = arr1>arr2
print(fillter)

[False  True  True]


색인과 슬라이딩

In [ ]:
arr=np.arange(10000)

In [ ]:
print(arr[5:8])

[5 6 7]


In [ ]:
print(arr[:8])

[0 1 2 3 4 5 6 7]


In [ ]:
print(arr[995:])

[ 995  996  997 ... 9997 9998 9999]


In [ ]:
arr=np.zeros(30)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [ ]:
arr[5:8]=7
print(arr)

[0. 0. 0. 0. 0. 7. 7. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr[0])
print(arr[1])
print(arr[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
print(arr[0][2])

3


In [ ]:
print(arr[0,2])

3


In [ ]:
#소스 배열을 가지고 간단한 실험을 하기 위해서 복사하여 사용하기
cp_arr=arr.copy()
print(cp_arr)
cp_arr=cp_arr*2
print(cp_arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
cp_arr=arr
print(cp_arr)
cp_arr=cp_arr*2
print(cp_arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
cp_arr=arr.copy()
print(cp_arr)
cp_arr[0][1]=8
print(cp_arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
cp_arr=arr
print(cp_arr)
cp_arr[0][1]=8
print(cp_arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr=np.array([1,2,3])

filter=arr>=2
print(filter)

[False  True  True]


In [ ]:
res=arr[filter]
print(res)

[2 3]


In [ ]:
res=arr[~filter]
print(res)

[1]


구조변경

In [ ]:
arr=np.arange(96)
print("구조:",arr.shape)
print("차원:",arr.ndim)

구조: (96,)
차원: 1


In [ ]:
arr2=arr.reshape((6,16))
print("구조:",arr2.shape)
print("차원:",arr2.ndim)

구조: (6, 16)
차원: 2


In [ ]:
#arr2=arr.reshape((7,14))#7*n이 96이 아니라서 오류
#print("구조:",arr2.shape)
#print("차원:",arr2.ndim)

ValueError: ignored

In [ ]:
arr2=arr.reshape((6,-1))#구조 변경 요청할 때 하나의 차원은 -1로 표현 가능(알아서 계산)
print("구조:",arr2.shape)
print("차원:",arr2.ndim)

구조: (6, 16)
차원: 2


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
arr2=arr.T#전치 행렬
print(arr)
print("==================")
print(arr2)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr2=arr.transpose()#arr.T와 같은 결과를 반환
print(arr)
print("========")
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr2 = np.sqrt(arr)
print(arr2)
print(arr)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr1=np.random.randn(2,3)
print(arr1)
print("=======================================")
arr2=np.random.randn(2,3)
print(arr2)

[[-0.00349364 -0.19965909  0.79310464]
 [ 0.74560392 -0.08969502 -0.91942196]]
[[ 0.33836676  1.14806694  1.21377459]
 [-1.06915376 -0.127334   -0.01237383]]


In [ ]:
arr3=np.maximum(arr1,arr2)
print(arr3)

[[ 2.59242395 -0.90571143  0.22451865]
 [ 1.73983155  1.22611494  0.18638785]]


Numpy안으로

In [ ]:
#잠시 파이썬 기본 문법 - 리스트 컴프리헨션
xs = [x*x+2*x+3 for x in range(1,10)] #리스트 컴프리헨션
print(xs)

[6, 11, 18, 27, 38, 51, 66, 83, 102]


In [ ]:
xs=[]
for x in range(1,10):
  xs.append(x*x+2*x+3)
print(xs)

[6, 11, 18, 27, 38, 51, 66, 83, 102]


In [ ]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])

In [ ]:
#파이썬 기초 문법 - zip 사용 예
ls1=[1,2,3]
ls2=['가','나','다']
for e1,e2 in zip(ls1,ls2):
  print(e1,e2)

1 가
2 나
3 다


In [ ]:
#리스트 컴프리헨션
result = [(x if c else y) for x,y,c in zip(xarr,yarr,cond)]
print(result)

[1.1, 2.2, 1.3, 1.4, 2.5]


In [ ]:
result=[]#위랑 같은거
for x,y,c in zip(xarr,yarr,cond):
  if c:
    result.append(x)
  else:
    result.append(y)
print(result)

[1.1, 2.2, 1.3, 1.4, 2.5]


In [ ]:
result= np.where(cond,xarr,yarr)
print(result)

[1.1 2.2 1.3 1.4 2.5]


In [ ]:
result=np.where(cond,1,2)
print(result)

[1 2 1 1 2]


In [ ]:
heights=np.random.normal(172.4,5,100)#평균 172.4 표준편차 5인 표본 100개를 생성
print(heights)

[169.91700463 165.65887559 166.5602653  169.14224681 171.59168397
 176.53905527 168.18328715 171.46910173 167.86892521 163.94796794
 179.58947676 176.52188753 162.75609025 175.90614518 164.33697146
 180.04780209 175.17867214 168.4578146  169.80211153 178.40858299
 170.54550434 178.42793868 177.43047707 170.98037382 169.78452516
 176.84230315 172.2640954  168.53546401 176.82628714 171.46538509
 177.96100658 171.61215586 163.92540205 180.93654925 178.35068552
 164.47335403 168.39811552 170.00012645 168.24486925 176.10583558
 172.68633249 170.64442347 175.67691771 177.69962658 171.46210726
 172.41520179 176.38642041 170.03705838 164.09743088 166.22772255
 176.04122282 171.29921032 176.06615287 177.35944225 168.18620273
 167.53313015 169.90734106 176.41035815 173.67776099 176.87061619
 166.12747719 167.91061202 172.15663346 164.66957599 163.91526917
 163.42336874 174.84115349 172.08575957 165.75041973 175.65649993
 175.64493124 173.84473365 173.79188942 176.39551503 177.68465089
 168.18557

In [ ]:
print("평균:",heights.mean())#print("평균:",np.mean(heights))
print("합계:",heights.sum()) #print("합계:",np.sum(heights))

평균: 171.9020115656469
합계: 17190.20115656469


In [ ]:
h2=heights.reshape(20,-1)
print("구조:",h2.shape)
print(h2)

구조: (20, 5)
[[169.91700463 165.65887559 166.5602653  169.14224681 171.59168397]
 [176.53905527 168.18328715 171.46910173 167.86892521 163.94796794]
 [179.58947676 176.52188753 162.75609025 175.90614518 164.33697146]
 [180.04780209 175.17867214 168.4578146  169.80211153 178.40858299]
 [170.54550434 178.42793868 177.43047707 170.98037382 169.78452516]
 [176.84230315 172.2640954  168.53546401 176.82628714 171.46538509]
 [177.96100658 171.61215586 163.92540205 180.93654925 178.35068552]
 [164.47335403 168.39811552 170.00012645 168.24486925 176.10583558]
 [172.68633249 170.64442347 175.67691771 177.69962658 171.46210726]
 [172.41520179 176.38642041 170.03705838 164.09743088 166.22772255]
 [176.04122282 171.29921032 176.06615287 177.35944225 168.18620273]
 [167.53313015 169.90734106 176.41035815 173.67776099 176.87061619]
 [166.12747719 167.91061202 172.15663346 164.66957599 163.91526917]
 [163.42336874 174.84115349 172.08575957 165.75041973 175.65649993]
 [175.64493124 173.84473365 173.7918

In [ ]:
print("평균(축0):",h2.mean(axis=0)) #컬럼 별 평균
print("평균(축1):",h2.mean(axis=1)) #로우 별 평균

평균(축0): [172.68374699 171.49525507 171.88482515 171.69550717 171.75072345]
평균(축1): [168.57401526 169.60166746 171.82211424 174.37899667 173.43376381
 173.18670696 174.55715985 169.44446017 173.6338815  169.8327668
 173.7904462  172.87984131 166.95591356 170.35144029 175.47234405
 170.91644824 172.17540809 171.58296572 172.86086313 172.58902802]


In [ ]:
print("합계(축0):",h2.sum(axis=0)) #컬럼 별 합계
print("합계(축1):",h2.sum(axis=1)) #로우 별 합계

합계(축0): [3453.67493989 3429.90510134 3437.69650303 3433.91014334 3435.01446896]
합계(축1): [842.8700763  848.0083373  859.11057119 871.89498335 867.16881907
 865.93353479 872.78579926 847.22230083 868.16940749 849.163834
 868.952231   864.39920654 834.77956782 851.75720146 877.36172023
 854.58224118 860.87704043 857.91482859 864.30431565 862.94514009]


In [ ]:
print("분산(축0):",h2.var())
print("표준편차:",h2.std()) 

분산(축0): 20.99308135017244
표준편차: 4.5818207461851275


In [ ]:
print("최솟값:",h2.min())
print("최댓값:",h2.max()) 

최솟값: 162.7560902512109
최댓값: 180.9365492506176


In [ ]:
print("최솟값이 있는 위치:",heights.argmin())
print("최댓값이 있는 위치:",heights.argmax()) 
print(heights[heights.argmin()],heights[heights.argmax()])

최솟값이 있는 위치: 12
최댓값이 있는 위치: 33
162.7560902512109 180.9365492506176


In [ ]:
arr=np.array([1,2,4,2,7])
print("누적합계:",arr.cumsum())
print("누적곱:",arr.cumprod())

누적합계: [ 1  3  7  9 16]
누적곱: [  1   2   8  16 112]


In [ ]:
s_arr=arr.sort()
print(arr)

[1 2 2 4 7]


In [ ]:
ua=np.unique(arr)
print(ua)

[1 2 4 7]


In [ ]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[2,3],[1,2],[4,5]])
re=x.dot(y)
print(x)
print("=============")
print(y)
print("=============")
print(re)

[[1 2 3]
 [4 5 6]]
[[2 3]
 [1 2]
 [4 5]]
[[16 22]
 [37 52]]


# 난수

In [ ]:
for _ in range(10): #_ 의미없음. 변수를 굳이 쓰지 않겠다는 의미
  print(np.random.uniform(-2,3)) #-2에서 3까지 랜덤하게 실수를 반환

0.869278938898185
-0.6777502491521159
0.4762644287162461
2.668225565197429
0.7906828117711187
1.331098238621673
-1.8880711797383358
0.579877407951872
1.8549534867324775
-1.625361636011685


In [ ]:
for _ in range(20):
  print(np.random.randint(1,5),end=' ')#1에서 5까지 랜덤하게 정수를 반환
print()

3 4 2 3 1 4 3 1 1 2 1 4 2 4 3 3 4 4 4 2 


In [ ]:
volan=[1,7,2,8,9]
for _ in range(20):
  print(np.random.choice(volan), end=' ')
print()

1 2 9 1 9 9 8 7 8 2 2 7 9 8 8 9 2 8 9 9 


In [ ]:
np.random.seed(100)